# StopTimer 插件設定檔

# 是否啟用BOSSBAR功能
BossBar: true

messages:
  command:
    # 指令使用說明
    usage: "&c使用方式: /stopserver <時間> or /stopserver cancel"
    # 沒有權限時顯示
    nopermission: "&c你沒有權限使用這個指令."
    # 錯誤時間格式
    errorformat: "&c未知的時間格式! 使用：s,m,h."
    # 倒數已取消
    canceled: "&a倒數已取消."
    # 沒有倒數時取消
    cancelfail: "&c沒有正在運行的倒數計時."
    # 設定重新載入
    reload: "&aStopTimer 設定已重新載入!"
  notify:
    # 標題通知
    title: "&c&l重啟通知"
    # 子標題通知，%time% 會被替換成時間
    subtitle: "&4伺服器將在 &c%time% &4後重啟"
    message:
      - "&c&l重啟通知"
      - "&4伺服器將在 &c%time% &4後重啟"
    # 斷線訊息
    kick: "&c伺服器正在重啟，請稍後再試"
    cancel:
      - "&c&l重啟通知"
      - "&4伺服器重啟已取消"
  bossbar:
    # bossbar顯示內容
    message: "&4&l伺服器將在 &c&l%time% &4&l後重啟"
  placeholder:
    # PlaceholderAPI 提示訊息
    message: "&4&l伺服器將在 &c&l%time% &4&l後重啟"
  discord:
    # Discord通知
    message: "## :warning: 伺服器將在 %time% 後重啟"
    # Discord取消通知
    cancel: "## :warning: 伺服器重啟已取消"

NotifyTime:
  Title:
    # 是否一開始就發送 Title 通知
    FirstRun: false
    # 幾秒時發送 Title 通知
    Seconds:
      - 300
      - 60
      - 10
      - 5
      - 4
      - 3
      - 2
      - 1
  Message:
    # 是否一開始就發送聊天訊息
    FirstRun: true
    # 幾秒時發送聊天訊息
    Seconds:
      - 1800
      - 600
      - 300
      - 60
      - 10
      - 5
      - 4
      - 3
      - 2
      - 1
  Discord:
    # 是否一開始就發送 Discord 通知
    FirstRun: true
    # 幾秒時發送 Discord 通知
    Seconds:
      - 1800
      - 600
      - 300
      - 60
      - 10