# StopTimer plugin configuration file

Language: "en_us" # Language setting

Bossbar:
  # Enable BOSSBAR feature
  Enable: true
  # Bossbar color
  Color: "RED"
  # Bossbar style
  Style: "SOLID"

NotifyTime:
  Title: # (with sound effect)
    # Whether to send Title notification at the beginning
    FirstRun: false
    # Seconds to send Title notification
    Seconds:
      - 300
      - 60
      - 10
      - 5
      - 4
      - 3
      - 2
      - 1
  Message:
    # Whether to send chat message at the beginning
    FirstRun: true
    # Seconds to send chat message
    Seconds:
      - 1800
      - 600
      - 300
      - 60
      - 10
      - 5
      - 4
      - 3
      - 2
      - 1
  Discord:
    # Enable Discord notification
    Enable: true
    # Whether to send Discord notification at the beginning
    FirstRun: true
    # Seconds to send Discord notification
    Seconds:
      - 1800
      - 600
      - 300
      - 60
      - 10