name: StopTimer
version: '1.2'
main: me.xydesu.stoptimer.Main
api-version: '1.21'
authors: [xydesu]
depend: [PlaceholderAPI, DiscordSRV]
commands:
  stopserver:
    description: Stops the server and displays the time taken to stop.
    usage: /<command>